"""changes_2

Revision ID: 3da11d6ee21e
Revises: 
Create Date: 2025-03-29 01:02:14.830989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da11d6ee21e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_conversion_counts', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_variants_experiment_id'), ['experiment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variants_experiment_id'))
        batch_op.drop_column('step_conversion_counts')

    # ### end Alembic commands ###
