"""Initial migration

Revision ID: 7ff51bcb75bf
Revises: 
Create Date: 2025-03-28 23:29:31.394356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff51bcb75bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funnel_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('funnel_step_id', sa.Integer(), nullable=False),
    sa.Column('converted_count', sa.Integer(), nullable=False),
    sa.Column('posterior_mean', sa.Float(), nullable=True),
    sa.Column('ci_lower_95', sa.Float(), nullable=True),
    sa.Column('ci_upper_95', sa.Float(), nullable=True),
    sa.Column('prob_vs_control', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['funnel_step_id'], ['funnel_steps.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_results')
    op.drop_table('variants')
    op.drop_table('funnel_steps')
    op.drop_table('experiments')
    # ### end Alembic commands ###
